wandb:
  entity: "poludmik"
  project: "czech-llm"
dataset: "datasets/downloads/requests_translated_0_to_10k_google_gemma-2-2b-it/"
hyperparameters:
  seed: 228
  split_ratio: 0.005 # % of the data is used for validation
  output_dir: "training/lora/cp/instruction_gemma2-2b-it"
  overwrite_output_dir: True
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  eval_accumulation_steps: 1
  eval_steps: 5
  optim: "paged_adamw_32bit"
  save_steps: 1000
  logging_steps: 100
  group_by_length: True
  ddp_find_unused_parameters: False
  run_name: "LoRA_Gemma2-2b-it_Instr"
  learning_rate: 0.0001
  max_grad_norm: 1.0
  max_steps: 50000
  warmup_ratio: 0.1
  weight_decay: 0.1
  # fp16: True
  evaluation_strategy: "steps"
  lr_scheduler_type: "cosine"
  # min_lr_ratio: 0.3 # last_lr = min_lr_ratio * learning_rate
  gradient_checkpointing: True
  neftune_noise_alpha: 0.1
  trainer:
    # max_seq_length: 1520 # isn't used
  lora_config:
    r: 32
    alpha: 16
    dropout: 0.05
    target_modules: ["embed_tokens", "gate_proj", "q_proj", "v_proj", "k_proj", "o_proj", 'down_proj', 'up_proj']
    bias: "none"
    task_type: "CAUSAL_LM"
